services:
  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=autoflex123
      - APP_USER=inventory_user
      - APP_USER_PASSWORD=inventory_pass